---
- name: Testing andrewrothstein.consul_template
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'consul-template --version'
      ansible.builtin.command: /usr/local/bin/consul-template --version
      changed_when: false
      register: consul_template_test_output
    - name: Output of 'consul-template --version'
      ansible.builtin.debug:
        msg: '{{ consul_template_test_output.stdout }}'
