---
- name: check for install in {{ consul_template_install_dir }}
  become: yes
  stat:
    path: '{{ consul_template_install_dir }}'
  changed_when: False
  register: consul_template_binary
- when: not consul_template_binary.stat.exists
  block:
    - name: downloading {{ consul_template_zip_url }}
      become: '{{ consul_template_privilege_escalate }}'
      become_user: root
      get_url:
        url: '{{ consul_template_zip_url }}'
        dest: '{{ consul_template_tmp_zip }}'
        mode: 0644

    - name: mkdir {{ consul_template_install_dir }}
      become: '{{ consul_template_privilege_escalate }}'
      become_user: root
      file:
        path: '{{ consul_template_install_dir }}'
        state: directory
        mode: 0755

    - name: unarchive {{ consul_template_tmp_zip }}
      become: '{{ consul_template_privilege_escalate }}'
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ consul_template_tmp_zip }}'
        dest: '{{ consul_template_install_dir }}'
        creates: '{{ consul_template_install_dir }}/consul-template'
  always:
    - name: rm {{ consul_template_tmp_zip }}
      become: '{{ consul_template_privilege_escalate }}'
      become_user: root
      file:
        path: '{{ consul_template_tmp_zip }}'
        state: absent
- name: linking {{ consul_template_link }} to {{ consul_template_exe }}
  become: '{{ consul_template_privilege_escalate }}'
  become_user: root
  file:
    src: '{{ consul_template_exe }}'
    dest: '{{ consul_template_link }}'
    state: link
