---
- name: Installing consul-template binaries
  ansible.builtin.include_role:
    name: andrewrothstein.hashi
  vars:
    hashi_apps:
      - name: '{{ consul_template_app.name | default("consul-template") }}'
        ver: '{{ consul_template_app.ver | default(consul_template_ver) }}'
        meta: '{{ consul_template_app.meta | default("") }}'
